language: node_js
node_js:
  - "13"

install:
  - npm install

script:
  - ./node_modules/.bin/license-checker --onlyAllow 'MIT;Apache-2.0;ISC;BSD-3-Clause;BSD-2-Clause;AFLv2.1;AGPL-3.0;CC-BY-3.0;CC0-1.0;Unlicense'
  - ./node_modules/.bin/eslint ./src/
  - npm test
  - coveralls < coverage/lcov.info
